### ISSUE TITLE
Non-nullable Edm.Date inescapable error "A nonnullable DataProperty cannot have a null defaultValue"

### ISSUE THREAD

**Issue by PhilBlackRose** [Breeze/breeze-client#7]
When using a scalar property with datatype of Edm.Date, specified in CSDL:

```
<Property Name="StartDate" Nullable="false" Type="Edm.Date"/>
```

Without a defaultValue attribute, breeze-client throws a metadata parsing error.

```
{
   description: "Metadata query failed for /odata/$metadata; Unable to process returned metadata: A nonnullable DataProperty cannot have a null defaultValue. Name: StartDate", 
   message: "Metadata query failed for /odata/$metadata; Unable to process returned metadata: A nonnullable DataProperty cannot have a null defaultValue. Name: StartDate", 
   stack: "Error: Metadata query failed for /odata/$metadata; Unable to process returned metadata: A nonnullable DataProperty cannot have a null defaultValue. Name: StartDate at Anonymous function (https://localhost:44325/lib_node/bundle.js:18795:25) at Anonymous function (https://localhost:44325/lib_node/bundle.js:44226:13) at Anonymous function (https://localhost:44325/lib_node/bundle.js:43822:21) at emitNone (https://localhost:44325/lib_node/bundle.js:21922:7) at emit (https://localhost:44325/lib_node/bundle.js:22002:7) at endReadableNT (https://localhost:44325/lib_node/bundle.js:37107:5) at afterTickTwo (https://localhost:44325/lib_node/bundle.js:32914:7) at Item.prototype.run (https://localhost:44325/lib_node/bundle.js:33087:5) at drainQueue (https://localhost:44325/lib_node/bundle.js:33057:17)"}
```

The problem is, with this odata server, the defaultValue can't be specified in the CSDL metadata, so a workaround is not possible. It does not seem possible to allow breeze-client to continue parsing then supply a defaultValue later via javascript.

Using breeze-client@1.7.1
Web API Odata

**Comment by steveschmitt** [comment]
Fixed in release **2.1.0**
